name: Content Pipeline

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create credentials file
      run: |
        echo '${{ secrets.GOOGLE_CREDENTIALS }}' > src/content-pipeline-bot-key.json
    
    - name: Check and migrate Google Sheets schema
      run: |
        cd src
        python ../scripts/verify_sheets_schema.py || python ../scripts/migrate_sheets_schema.py --auto-confirm
      env:
        PYTHONPATH: ${{ github.workspace }}/src
      continue-on-error: true
    
    - name: Run content pipeline
      run: |
        cd src
        python -m content_pipeline.main --strategy enhanced --log-level INFO
      env:
        PYTHONPATH: ${{ github.workspace }}/src
    
    - name: Format Google Sheets
      run: |
        python scripts/format_google_sheets.py
      env:
        PYTHONPATH: ${{ github.workspace }}/src
      continue-on-error: true
    
    - name: Upload logs (on failure)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: pipeline-logs
        path: |
          *.log
          logs/