name: Content Pipeline

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create credentials file
      run: |
        echo '${{ secrets.GOOGLE_CREDENTIALS }}' > content-pipeline-bot-key.json
    
    - name: Run content pipeline
      run: |
        cd src
        python -m content_pipeline.main
      env:
        PYTHONPATH: ${{ github.workspace }}/src
    
    - name: Upload logs (on failure)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: pipeline-logs
        path: |
          *.log
          logs/